# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74f8b5c6e46e71e9040963a70c6974a36e887ecb9efd5433d74ba68ee33ca53b9ed75aa0032d0cd231eece3145467ca916cfc9b6fafb94fb2beadf491fd4a9fe

test:
  secret_key_base: 9d07552ce00039e71bcd39949455fc104c91e22eed58e9de79d1de21fe43232d5e54b192e87b0ebb0ab4e839dfed3b77f3d26f4ff519fe33d8191ebb7b6c241e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
